"""T07 — xterm escape-sequence fixture conformance via the Session pipeline.

Vendored from xterm.js (`fixtures/escape_sequence_files`): `.in`/`.text`
pairs generated by the escseq corpus on a pty. Each `.in` is fed through
the full pipeline and `render()` is diffed against the expected `.text`
at 80×25.

Phase 4 rewired the harness: every fixture now runs through a real
`Session` (ADR-0005) instead of a bare `Parser.feed`. The non-pty
fixtures are the child's byte stream, served to the reader thread by a
chunked fake pty — every read lands on a partial-escape boundary, so the
whole corpus exercises the T6 invariant (dispatch pending printables at
each read boundary). t0004-LF's `.in` is *typed input* (its `.text`
includes the driver echo), so it still needs a real pty.

Corpus conventions handled here:
- the corpus was generated through a pty, so a bare LF reached the
  terminal as CR LF (onlcr) — we normalize the same way before feeding;
- `.text` rows keep their trailing spaces on content rows, but blank rows
  are empty strings (the 26th split-line is just the trailing newline).
"""

from __future__ import annotations

import os
import pathlib
import sys
import time

import pytest

from pyqtermx.ptyspawn import Pty
from pyqtermx.session import Session

from tests.pty.test_pty import wait_for
from tests.session.test_session import FakePty

FIXTURES = pathlib.Path(__file__).parent / "fixtures" / "escape_sequence_files"

#: Fixtures reproducible only through a pty (echo comes from the driver).
PTY_FIXTURES: dict[str, str] = {
    "t0004-LF": "generated with terminal echo ON; the pty driver echoes the typed input",
}

FILES = sorted(
    path.name[: -len(".in")]
    for path in FIXTURES.glob("*.in")
    if path.name[: -len(".in")] not in PTY_FIXTURES
)


class _ChunkedFakePty(FakePty):
    """FakePty served in fixed slices — every read lands on a mid-escape
    boundary (deterministic: no sleeps needed, and select() keeps firing
    while data remains in the pipe). Tracks how much the reader thread
    has consumed for drain detection."""

    def __init__(self, chunk: int = 64, **kwargs) -> None:
        super().__init__(**kwargs)
        self._chunk = chunk
        self.total_read = 0

    def read(self) -> bytes | None:
        if self.closed:
            return None
        try:
            data = os.read(self._r, self._chunk)
        except BlockingIOError:
            return b""
        except OSError:
            return None
        if data == b"":
            return None
        self.total_read += len(data)
        return data


def _fixture_bytes(name: str) -> bytes:
    data = (FIXTURES / f"{name}.in").read_bytes()
    return data.decode("utf-8").replace("\n", "\r\n").encode()  # pty onlcr


def _run_via_session(name: str) -> list[str]:
    """Serve the fixture's `.in` to the reader thread in chunks; return
    the rendered rows once the stream is drained and snapshots settle."""
    fake = _ChunkedFakePty(rows=25, cols=80)
    session = Session(fake, lines=25, columns=80)
    session.start()
    try:
        data = _fixture_bytes(name)
        fake.output(data)
        # Drain: all bytes consumed by the reader thread.
        assert wait_for(lambda: fake.total_read >= len(data))
        # The final chunk's snapshot is emitted right after its read;
        # wait for the snapshot count to settle, then render.
        deadline = time.monotonic() + 5.0
        previous = -1
        stable = 0
        while time.monotonic() < deadline:
            current = len(session.snapshots)
            if current == previous:
                stable += 1
                if stable >= 3:
                    break
            else:
                stable = 0
            previous = current
            time.sleep(0.05)
        return session.screen.render().split("\n")
    finally:
        session.close()


def _run_via_pty(name: str) -> list[str]:
    """Type the fixture's `.in` through a real pty (chunked, like a
    user): the driver echoes the input, the no-op child just reads.
    Returns the rendered rows once the screen is quiescent."""
    pty = Pty(
        [sys.executable, "-c", "import sys\nsys.stdin.read()\n"],
        rows=25,
        cols=80,
    )
    session = Session(pty, lines=25, columns=80)
    session.start()
    try:
        data = (FIXTURES / f"{name}.in").read_bytes()
        for i in range(0, len(data), 7):
            session.send_data(data[i : i + 7])
        # Quiescence: three consecutive identical renders (~150 ms of
        # stability — the first equal pair can be a pre-echo state).
        deadline = time.monotonic() + 5.0
        previous = None
        stable = 0
        while time.monotonic() < deadline:
            current = session.screen.render()
            if current == previous:
                stable += 1
                if stable >= 3:
                    break
            else:
                stable = 0
            previous = current
            time.sleep(0.05)
        return session.screen.render().split("\n")
    finally:
        session.close()


def _expected(name: str) -> list[str]:
    content = (FIXTURES / f"{name}.text").read_text(encoding="utf-8")
    rows = content.split("\n")
    return rows[:-1] if rows[-1] == "" else rows


def _assert_rows(actual: list[str], expected: list[str]) -> None:
    assert len(actual) == len(expected) == 25
    for y, exp in enumerate(expected):
        row = actual[y]
        if exp == "":
            assert row.strip(" ") == "", f"row {y}: expected blank, got {row!r}"
        else:
            assert row.startswith(exp), (
                f"row {y}: expected {exp!r}, got {row!r}"
            )
            assert row[len(exp):].strip(" ") == "", (
                f"row {y}: unexpected content past {exp!r} in {row!r}"
            )


@pytest.mark.parametrize("name", FILES)
def test_escape_sequence_fixture(name: str) -> None:
    _assert_rows(_run_via_session(name), _expected(name))


@pytest.mark.parametrize("name", sorted(PTY_FIXTURES))
def test_escape_sequence_fixture_via_pty(name: str) -> None:
    """Fixtures whose `.in` holds the typed input and whose `.text`
    includes the terminal's echo — reproducible only through a pty."""
    _assert_rows(_run_via_pty(name), _expected(name))
